# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "d43e43bdac99cfaabd071c040e01809f"
name = "combine-order"
handle = "combine-order-3"
application_url = "https://combine-app-18c1e26d7ea5.herokuapp.com/"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "barcode-testing.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_orders,write_draft_orders,write_orders,write_products"

[auth]
redirect_urls = [
  "https://combine-app-18c1e26d7ea5.herokuapp.com/auth/callback"
]

[webhooks]
api_version = "2024-10"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks"

[pos]
embedded = false
